driver:
  name: vagrant
  forward_agent: true
  customize:
    cpus: 2
    memory: 2048
  network:
    - ['private_network', {ip: '10.10.33.33', netmask: '255.255.0.0'}]

  synced_folders:
    - ['.', '/home/vagrant/hem', 'create: true, type: :nfs']
    - ['~/.gnupg', '/home/vagrant/.gnupg']
  vagrantfiles:
    - Vagrantfile.forward_agent.rb

provisioner:
  require_chef_omnibus: 12

platforms:
  - name: bento/ubuntu-16.04
  - name: bento/centos-6.7
  - name: bento/debian-7.8

suites:
  - name: default
    run_list:
      - omnibus::default
      - hem-build::default
    attributes:
      hem-build:
        gpg_userdir: /home/vagrant
        gpg_name: B8D64BCB
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/hem
        install_dir: /opt/hem
